/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "net.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct Utilisateur *
inscription_1(struct Utilisateur *argp, CLIENT *clnt)
{
	static struct Utilisateur clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, INSCRIPTION,
		(xdrproc_t) xdr_Utilisateur, (caddr_t) argp,
		(xdrproc_t) xdr_Utilisateur, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct Abonnement *
ajout_abonnement_1(struct Abonnement *argp, CLIENT *clnt)
{
	static struct Abonnement clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, AJOUT_ABONNEMENT,
		(xdrproc_t) xdr_Abonnement, (caddr_t) argp,
		(xdrproc_t) xdr_Abonnement, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct Slot *
creation_slot_1(struct Slot *argp, CLIENT *clnt)
{
	static struct Slot clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CREATION_SLOT,
		(xdrproc_t) xdr_Slot, (caddr_t) argp,
		(xdrproc_t) xdr_Slot, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct Slot *
recherche_slot_1(struct Utilisateur *argp, CLIENT *clnt)
{
	static struct Slot clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, RECHERCHE_SLOT,
		(xdrproc_t) xdr_Utilisateur, (caddr_t) argp,
		(xdrproc_t) xdr_Slot, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct Paiement *
paiement_slot_1(struct Paiement *argp, CLIENT *clnt)
{
	static struct Paiement clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, PAIEMENT_SLOT,
		(xdrproc_t) xdr_Paiement, (caddr_t) argp,
		(xdrproc_t) xdr_Paiement, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

bool_t *
supprimer_compte_1(struct Utilisateur *argp, CLIENT *clnt)
{
	static bool_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, SUPPRIMER_COMPTE,
		(xdrproc_t) xdr_Utilisateur, (caddr_t) argp,
		(xdrproc_t) xdr_bool, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct Abonnement *
modifier_abonnement_1(struct Abonnement *argp, CLIENT *clnt)
{
	static struct Abonnement clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MODIFIER_ABONNEMENT,
		(xdrproc_t) xdr_Abonnement, (caddr_t) argp,
		(xdrproc_t) xdr_Abonnement, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct Slot *
modifier_slot_1(struct Slot *argp, CLIENT *clnt)
{
	static struct Slot clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, MODIFIER_SLOT,
		(xdrproc_t) xdr_Slot, (caddr_t) argp,
		(xdrproc_t) xdr_Slot, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

void *
historique_paiements_1(struct Utilisateur *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, HISTORIQUE_PAIEMENTS,
		(xdrproc_t) xdr_Utilisateur, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}
