/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "net.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
spliiit_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		struct Utilisateur inscription_1_arg;
		struct Abonnement ajout_abonnement_1_arg;
		struct Slot creation_slot_1_arg;
		struct Utilisateur recherche_slot_1_arg;
		struct Paiement paiement_slot_1_arg;
		struct Utilisateur supprimer_compte_1_arg;
		struct Abonnement modifier_abonnement_1_arg;
		struct Slot modifier_slot_1_arg;
		struct Utilisateur historique_paiements_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case INSCRIPTION:
		_xdr_argument = (xdrproc_t) xdr_Utilisateur;
		_xdr_result = (xdrproc_t) xdr_Utilisateur;
		local = (char *(*)(char *, struct svc_req *)) inscription_1_svc;
		break;

	case AJOUT_ABONNEMENT:
		_xdr_argument = (xdrproc_t) xdr_Abonnement;
		_xdr_result = (xdrproc_t) xdr_Abonnement;
		local = (char *(*)(char *, struct svc_req *)) ajout_abonnement_1_svc;
		break;

	case CREATION_SLOT:
		_xdr_argument = (xdrproc_t) xdr_Slot;
		_xdr_result = (xdrproc_t) xdr_Slot;
		local = (char *(*)(char *, struct svc_req *)) creation_slot_1_svc;
		break;

	case RECHERCHE_SLOT:
		_xdr_argument = (xdrproc_t) xdr_Utilisateur;
		_xdr_result = (xdrproc_t) xdr_Slot;
		local = (char *(*)(char *, struct svc_req *)) recherche_slot_1_svc;
		break;

	case PAIEMENT_SLOT:
		_xdr_argument = (xdrproc_t) xdr_Paiement;
		_xdr_result = (xdrproc_t) xdr_Paiement;
		local = (char *(*)(char *, struct svc_req *)) paiement_slot_1_svc;
		break;

	case SUPPRIMER_COMPTE:
		_xdr_argument = (xdrproc_t) xdr_Utilisateur;
		_xdr_result = (xdrproc_t) xdr_bool;
		local = (char *(*)(char *, struct svc_req *)) supprimer_compte_1_svc;
		break;

	case MODIFIER_ABONNEMENT:
		_xdr_argument = (xdrproc_t) xdr_Abonnement;
		_xdr_result = (xdrproc_t) xdr_Abonnement;
		local = (char *(*)(char *, struct svc_req *)) modifier_abonnement_1_svc;
		break;

	case MODIFIER_SLOT:
		_xdr_argument = (xdrproc_t) xdr_Slot;
		_xdr_result = (xdrproc_t) xdr_Slot;
		local = (char *(*)(char *, struct svc_req *)) modifier_slot_1_svc;
		break;

	case HISTORIQUE_PAIEMENTS:
		_xdr_argument = (xdrproc_t) xdr_Utilisateur;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) historique_paiements_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (SPLIIIT_PROG, SPLIIIT_V1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SPLIIIT_PROG, SPLIIIT_V1, spliiit_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SPLIIIT_PROG, SPLIIIT_V1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SPLIIIT_PROG, SPLIIIT_V1, spliiit_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SPLIIIT_PROG, SPLIIIT_V1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
