/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "net.h"


void
spliiit_prog_1(char *host)
{
	CLIENT *clnt;
	struct Utilisateur  *result_1;
	struct Utilisateur  inscription_1_arg;
	struct Abonnement  *result_2;
	struct Abonnement  ajout_abonnement_1_arg;
	struct Slot  *result_3;
	struct Slot  creation_slot_1_arg;
	struct Slot  *result_4;
	struct Utilisateur  recherche_slot_1_arg;
	struct Paiement  *result_5;
	struct Paiement  paiement_slot_1_arg;
	bool_t  *result_6;
	struct Utilisateur  supprimer_compte_1_arg;
	struct Abonnement  *result_7;
	struct Abonnement  modifier_abonnement_1_arg;
	struct Slot  *result_8;
	struct Slot  modifier_slot_1_arg;
	void  *result_9;
	struct Utilisateur  historique_paiements_1_arg;
	
	// Initialisation des données de l'utilisateur
    strcpy(inscription_1_arg.nom, "Doe");
    strcpy(inscription_1_arg.prenom, "John");
    strcpy(inscription_1_arg.email, "john.doe@example.com");
    strcpy(inscription_1_arg.mot_de_passe, "password123");

#ifndef	DEBUG
	clnt = clnt_create (host, SPLIIIT_PROG, SPLIIIT_V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = inscription_1(&inscription_1_arg, clnt);
	if (result_1 == (struct Utilisateur *) NULL) {
		clnt_perror (clnt, "call failed");
	} else{
         printf("Utilisateur inscrit : %s %s\n", result_1->prenom, result_1->nom);
    }
    
	// Initialiser les données de l'abonnement
    strcpy(ajout_abonnement_1_arg.type, "Standard");
    ajout_abonnement_1_arg.prix_total = 100;
    ajout_abonnement_1_arg.nb_slots = 5;
    ajout_abonnement_1_arg.slots_disponibles = 5;
	result_2 = ajout_abonnement_1(&ajout_abonnement_1_arg, clnt);
	if (result_2 == (struct Abonnement *) NULL) {
		clnt_perror (clnt, "call failed");
	}else {
        printf("Abonnement ajouté avec ID: %d\n", result_2->id);
    }

	// Initialiser les données du slot
    creation_slot_1_arg.id_abonnement = 1; // Supposons que le slot appartient à l'abonnement 1
    strcpy(creation_slot_1_arg.nom_utilisateur, "User1");
    creation_slot_1_arg.prix_slot = 20.0f;

	result_3 = creation_slot_1(&creation_slot_1_arg, clnt);
	if (result_3 == (struct Slot *) NULL) {
		clnt_perror (clnt, "call failed");
	}else {
        printf("Slot créé avec ID: %d\n", result_3->id);
    }
    
	// Initialiser les données de l'utilisateur pour la recherche
    strcpy(recherche_slot_1_arg.nom, "User1");

	result_4 = recherche_slot_1(&recherche_slot_1_arg, clnt);
	if (result_4 == (struct Slot *) NULL) {
		printf("Aucun slot trouvé pour l'utilisateur %s\n", recherche_slot_1_arg.nom);
	}else {
        printf("Slot trouvé: ID %d, Utilisateur %s, Prix %f\n",
               result_4->id, result_4->nom_utilisateur, result_4->prix_slot);
    }
    
	// Initialiser les données de paiement
    paiement_slot_1_arg.id_slot = 1; // Supposons que le paiement est pour le slot 1
    paiement_slot_1_arg.montant = 20.0f;
    strcpy(paiement_slot_1_arg.date, "2023-04-01");

	result_5 = paiement_slot_1(&paiement_slot_1_arg, clnt);
	if (result_5 == (struct Paiement *) NULL) {
		clnt_perror (clnt, "call failed");
	}else {
        printf("Paiement enregistré: ID Slot %d, Montant %f, Date %s\n",
               result_5->id_slot, result_5->montant, result_5->date);
    }
    
	// Initialiser les données de l'utilisateur pour la suppression
    strcpy(supprimer_compte_1_arg.nom, "Doe");

	result_6 = supprimer_compte_1(&supprimer_compte_1_arg, clnt);
	if (result_6 == (bool_t *) NULL) {
		clnt_perror (clnt, "call failed");
	}else {
        if(*result_6) {
            printf("Compte de l'utilisateur %s supprimé avec succès.\n", supprimer_compte_1_arg.nom);
        } else {
            printf("Échec de la suppression du compte de l'utilisateur %s.\n", supprimer_compte_1_arg.nom);
        }
	}
	result_7 = modifier_abonnement_1(&modifier_abonnement_1_arg, clnt);
	if (result_7 == (struct Abonnement *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = modifier_slot_1(&modifier_slot_1_arg, clnt);
	if (result_8 == (struct Slot *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = historique_paiements_1(&historique_paiements_1_arg, clnt);
	if (result_9 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	spliiit_prog_1 (host);
exit (0);
}
