/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "net.h"

bool_t
xdr_Utilisateur (XDR *xdrs, Utilisateur *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nom, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->prenom, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->email, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->mot_de_passe, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Abonnement (XDR *xdrs, Abonnement *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->type, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->prix_total))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nb_slots))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->slots_disponibles))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Slot (XDR *xdrs, Slot *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id_abonnement))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nom_utilisateur, 40,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->prix_slot))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Paiement (XDR *xdrs, Paiement *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->id_slot))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->date, 10,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->montant))
		 return FALSE;
	return TRUE;
}
